services:
  frontend:
    container_name: skate-tracker-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    depends_on:
      - backend

  backend:
    container_name: skate-tracker-backend
    build:
      context: ./backend
    ports:
      - 4000:4000
